version: 2.1

container: &container
  docker:
    - image: circleci/node:10.16

jobs:
  run-vue-cli:
    <<: *container

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get install expect

      - restore_cache:
          keys:
          - vue-cli-{{ checksum "template/package.json" }}

      - run: npm install -g yarn
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: vue-cli-{{ checksum "template/package.json" }}

      - run: expect task/init.expect

      - restore_cache:
          keys:
          - project-{{ checksum "nuxt-project/package.json" }}-v1

      - run: cd nuxt-project && yarn install

      - save_cache:
          paths:
            - nuxt-project/node_modules
          key: project-{{ checksum "nuxt-project/package.json" }}-v1

      - run: cd nuxt-project && yarn build

      - run: cd nuxt-project && yarn generate

      - persist_to_workspace:
          root: ~/
          paths:
            - repo/nuxt-project/dist

workflows:
  version: 2.1
  commit:
    jobs:
      - run-vue-cli
